//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace WSBertoaldo.ORAWSVService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ORAWSVBinding", Namespace="http://xmlns.oracle.com/orawsv")]
    public partial class ORAWSVService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback XMLFromQueryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ORAWSVService() {
            this.Url = global::WSBertoaldo.Properties.Settings.Default.WSBertoaldo_ORAWSVService_ORAWSVService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event XMLFromQueryCompletedEventHandler XMLFromQueryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bertoaldo.valme.net:8081/orawsv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryOut", Namespace="http://xmlns.oracle.com/orawsv")]
        public System.Xml.XmlElement XMLFromQuery([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xmlns.oracle.com/orawsv")] query query) {
            object[] results = this.Invoke("XMLFromQuery", new object[] {
                        query});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void XMLFromQueryAsync(query query) {
            this.XMLFromQueryAsync(query, null);
        }
        
        /// <remarks/>
        public void XMLFromQueryAsync(query query, object userState) {
            if ((this.XMLFromQueryOperationCompleted == null)) {
                this.XMLFromQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXMLFromQueryOperationCompleted);
            }
            this.InvokeAsync("XMLFromQuery", new object[] {
                        query}, this.XMLFromQueryOperationCompleted, userState);
        }
        
        private void OnXMLFromQueryOperationCompleted(object arg) {
            if ((this.XMLFromQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XMLFromQueryCompleted(this, new XMLFromQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class query {
        
        private string[] dDL_textField;
        
        private queryQuery_text query_textField;
        
        private object[] itemsField;
        
        private queryNull_handling null_handlingField;
        
        private bool null_handlingFieldSpecified;
        
        private string max_rowsField;
        
        private string skip_rowsField;
        
        private bool pretty_printField;
        
        private bool pretty_printFieldSpecified;
        
        private string indentation_widthField;
        
        private string rowset_tagField;
        
        private string row_tagField;
        
        private bool item_tags_for_collField;
        
        private bool item_tags_for_collFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DDL_text")]
        public string[] DDL_text {
            get {
                return this.dDL_textField;
            }
            set {
                this.dDL_textField = value;
            }
        }
        
        /// <remarks/>
        public queryQuery_text query_text {
            get {
                return this.query_textField;
            }
            set {
                this.query_textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bind", typeof(queryBind))]
        [System.Xml.Serialization.XmlElementAttribute("bindXML", typeof(System.Xml.XmlElement))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public queryNull_handling null_handling {
            get {
                return this.null_handlingField;
            }
            set {
                this.null_handlingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool null_handlingSpecified {
            get {
                return this.null_handlingFieldSpecified;
            }
            set {
                this.null_handlingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string max_rows {
            get {
                return this.max_rowsField;
            }
            set {
                this.max_rowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string skip_rows {
            get {
                return this.skip_rowsField;
            }
            set {
                this.skip_rowsField = value;
            }
        }
        
        /// <remarks/>
        public bool pretty_print {
            get {
                return this.pretty_printField;
            }
            set {
                this.pretty_printField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pretty_printSpecified {
            get {
                return this.pretty_printFieldSpecified;
            }
            set {
                this.pretty_printFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string indentation_width {
            get {
                return this.indentation_widthField;
            }
            set {
                this.indentation_widthField = value;
            }
        }
        
        /// <remarks/>
        public string rowset_tag {
            get {
                return this.rowset_tagField;
            }
            set {
                this.rowset_tagField = value;
            }
        }
        
        /// <remarks/>
        public string row_tag {
            get {
                return this.row_tagField;
            }
            set {
                this.row_tagField = value;
            }
        }
        
        /// <remarks/>
        public bool item_tags_for_coll {
            get {
                return this.item_tags_for_collField;
            }
            set {
                this.item_tags_for_collField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool item_tags_for_collSpecified {
            get {
                return this.item_tags_for_collFieldSpecified;
            }
            set {
                this.item_tags_for_collFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class queryQuery_text {
        
        private queryQuery_textType typeField;
        
        private bool typeFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public queryQuery_textType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum queryQuery_textType {
        
        /// <remarks/>
        SQL,
        
        /// <remarks/>
        XQUERY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class queryBind {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum queryNull_handling {
        
        /// <remarks/>
        DROP_NULLS,
        
        /// <remarks/>
        NULL_ATTR,
        
        /// <remarks/>
        EMPTY_TAG,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void XMLFromQueryCompletedEventHandler(object sender, XMLFromQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XMLFromQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XMLFromQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591